version: '3.8'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - ELASTICSEARCH_HOST=es01
      - ELASTICSEARCH_PORT=9200
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - es01
    networks:
      - elastic
    ports:
      - "3000:3000"
  frontend:
    build: 
      context: ./frontend
      args:
        backend_url: backend
    depends_on:
      - backend
    networks:
      - elastic
    ports:
      - "80:80"
volumes:
  data01:
    driver: local
networks:
  elastic:
    driver: bridge
